name: Deploy to Cloudflare Pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Get current date
        run: echo "date=$(python -c "import datetime; print(datetime.datetime.utcnow().strftime('%a, %d %b %Y %X GMT'))")" >> $GITHUB_ENV

      - name: Format _headers
        run: sed -i "s/DATE/${{ env.date }}/g" public/_headers

#      - name: Commit changes
#        run: |
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git commit -m "Format _headers" -a

#      - name: Push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}

      - name: Install Node Dependencies
        run: npm install

      - name: Build React App
        run: CI=false && npm run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'chess-app'
          directory: 'build'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
