name: Deploy to Cloudflare Pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Get current date
        run: echo "date=$(python -c "import datetime; print(datetime.datetime.utcnow().strftime('%a, %d %b %Y %X GMT'))")" >> $GITHUB_ENV

      - name: Format _headers
        run: sed -i "s/DATE/${{ env.date }}/g" public/_headers

      - name: Install Node Dependencies
        run: yarn install

      - name: Build Next App
        run: yarn run staticbuild

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'chess-app'
          directory: 'out'
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear Cloudflare Cache
        run: |
          curl -XPOST \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://chessapp.ultras-playroom.xyz/service-worker.js"]}' \
          https://api.cloudflare.com/client/v4/zones/2c605334a67eb8cc841b11d0297b4542/purge_cache
